### ISSUE TITLE
The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by roberto-rodriguez** [daquinoaldo/https-localhost#28]
These are the logs:

Generating certificates...
[0] Certificates path: C:\Users\roberto.rodriguez\AppData\Roaming\https-localhost.  
[0] Downloading the mkcert executable...
[0] Running mkcert to generate certificates...
[0] (node:13992) UnhandledPromiseRejectionWarning: Error: Command failed: C:\Users\roberto.rodrigu4.exe -install -cert-file C:\Users\roberto.rodriguez\AppData\Roaming\https-localhost\localhost.crtocalhost\localhost.key localhost
[0] The process cannot access the file because it is being used by another process.
[0]
[0]     at ChildProcess.exithandler (child_process.js:294:12)
[0]     at ChildProcess.emit (events.js:182:13)
[0]     at maybeClose (internal/child_process.js:962:16)

**Comment by daquinoaldo** [comment]
Hi, which command do you use to run the script?

**Comment by camous** [comment]
I face the same situation when for the first attempt of calling ./serve (windows/powershell/administrator).

Running in a separate shell command
`mkcert-v1.4.1-windows-amd64.exe" -install -cert-file "C:\Users\username\AppData\Roaming\https-localhost\localhost.crt" -key-file "C:\Users\username\AppData\Roaming\https-localhost\localhost.key" localhost`

generated the certificate files and then `serve` was working just fine.

full error stack.
<pre>
Generating certificates...
Certificates path: C:\Users\username\AppData\Roaming\https-localhost. Never modify nor share this files.
Downloading the mkcert executable...
http to https redirection active.
Running mkcert to generate certificates...
(node:5160) UnhandledPromiseRejectionWarning: Error: Command failed: "C:\Users\username\AppData\Roaming\https-localhost\mkcert-v1.4.1-windows-amd64.exe" -install -cert-file "C:\Users\username\AppData\Roaming\https-localhost\localhost.crt" -key-file "C:\Users\username\AppData\Roaming\https-localhost\localhost.key" localhost
The process cannot access the file because it is being used by another process.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
(node:5160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ [Error: ENOENT: no such file or directory, open 'C:\"C:\Users\username\AppData\Roaming\https-localhost\mkcert.log"']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\"C:\\Users\\username\\AppData\\Roaming\\https-localhost\\mkcert.log"' }
{ [Error: ENOENT: no such file or directory, open 'C:\"C:\Users\username\AppData\Roaming\https-localhost\mkcert.err"']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\"C:\\Users\\username\\AppData\\Roaming\\https-localhost\\mkcert.err"' }
</pre>

**Comment by daquinoaldo** [comment]
Thabk

**Comment by daquinoaldo** [comment]
Hi @camous,
thank you for the additional information!
After launching an error, is the program able to serve pages on a secure connection? Or is it impossible without running mkcert manually?

**Comment by camous** [comment]
serve wasn't able to works with the error (I tested) beside the process was hanging.

I have the feeling the mkcert crashed/hang for some reasons (I was in administrator) making the promise fails.

when running mkcert manually (from command line directly), I think I remember I had a dialog box asking me to install the certificate in my local store (sorry I don't have the screen). maybe this dialog box on my windows version/laptop from works made the promise fails ?

**Comment by daquinoaldo** [comment]
Okay, thanks for the further investigation!

I suspect the error is within [this promise](https://github.com/daquinoaldo/https-localhost/blob/770a5b522ae00891433ea62ca021cbdb7fe3b06f/certs.js#L96), but I'm running out of time in these days.
If you want to try a fix on your own, you'll have all my support and thankfulness (and you'll be mentioned as contributor). Otherwise I'll try to fix it as soon as I can.

In any case, thank you for your time and for the precise information you already provided!

**Comment by camous** [comment]
little bit short on time, however, will quickly check if I can remove the installed certificate in order to re-produce the issue. that would be a first step :)

**Comment by robokozo** [comment]
I'm seeing the same thing.

```
Generating certificates...
Certificates path: C:\Users\username\AppData\Roaming\https-localhost. Never modify nor share this files.
Downloading the mkcert executable...
Running mkcert to generate certificates...
(node:32520) UnhandledPromiseRejectionWarning: Error: Command failed: "C:\Users\username\AppData\Roaming\https-localhost\mkcert-v1.4.1-windows-amd64.exe" -install -cert-file "C:\Users\username\AppData\Roaming\https-localhost\localhost.crt" -key-file "C:\Users\username\AppData\Roaming\https-localhost\localhost.key" localhost
The process cannot access the file because it is being used by another process.

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:32520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by daquinoaldo** [comment]
Hi guys,
thank you for reporting.

I've opened a branch for investigating the problem. I found path formatting error on macOS. I fixed on darwin architectures (see the above commit), but I need to test it on Windows. Anyway, probably the cause it will be the same.
I'm preparing a Windows test machine; I hope to work on a fix in the next days. Then I'll need your feedback.
Stay connected!

**Comment by daquinoaldo** [comment]
@robokozo @camous 
After some tests, the bug seems to be fixed. Could you please try again?

```sh
# uninstall any version of https-localhost (if any)
npm i -g https-localhost

# install the fixed version directly from the GitHub branch
npm install -g git://github.com/daquinoaldo/https-localhost.git#fix-issue-28
```

It should work.
If not, or if you have just a bit of time to make further investigations, please run the tests.
```sh
# uninstall any version of https-localhost (if any)
npm i -g https-localhost

# clone the fix-issue-28 branch of this repository
git clone -b fix-issue-28 https://github.com/daquinoaldo/https-localhost
# if you don't have git just download [this zip](https://github.com/daquinoaldo/https-localhost/archive/fix-issue-28.zip) and unzip it

# move into the folder
# should work also on Windows, but anyway, just open a terminal inside the directory you have cloned/downloaded
cd https-localhost

# install dependencies
npm i

# run tests
npm t

# if tests fail please paste here the output and run them again, second time should work
npm t
```

Troubleshooting: try to delete those two folders (it is safe, they are created by my script). Then try to install it or to run tests again.
```
C:\Users\aldod\AppData\Roaming\https-localhost
C:\Users\aldod\AppData\Local\mkcert
```

Thanks for your time, I really appreciate it.

**Comment by robokozo** [comment]
I ran the tests and this is the result:  
```

Testing certs
    √ can be uninstalled
    √ uninstall is idempotent (doesn't fail if called twice)
Generating certificates...
Certificates path: C:\Users\user\AppData\Roaming\https-localhost. Never modify nor share this files.
Downloading the mkcert executable...
Running mkcert to generate certificates...
(node:19640) UnhandledPromiseRejectionWarning: Error: Command failed: "C:\Users\user\AppData\Roaming\https-localh               ost\mkcert-v1.4.1-windows-amd64.exe" -install -cert-file "C:\Users\user\AppData\Roaming\https-localhost\localhost               .crt" -key-file "C:\Users\user\AppData\Roaming\https-localhost\localhost.key" localhost
The process cannot access the file because it is being used by another process.

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:19640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwin               g inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().                (rejection id: 1)
(node:19640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reje               ctions that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by daquinoaldo** [comment]
Thanks @robokozo!
Did this occur also the second time you ran the tests?

**Comment by robokozo** [comment]
Yes, I'm afraid so

**Comment by daquinoaldo** [comment]
I've ran other tests and even after many attempts I still unable to reproduce the issue. I tried to investigate the causes, but I can't find any parallelization errors: I await all the needed promises and call sync APIs on fs, the code is almost sequential.
I'm sorry for this. I'll be happy to help you if you can further investigate the problem and catch the bug origin.
Thank you for your comprehension.

**Comment by Xeonzinc** [comment]
Hi, probably not much help but I'm getting the same error on windows with your 'fix-issue-28' version. And as others have mentioned running the exact same command mentioned in the error manually works correctly strangely.

**Comment by NoelJacob** [comment]
Hey, probably you know it but, I npm installed the `fix-issue-28` version and everything works perfectly. I also git cloned `fix-issue-28` and ran the tests; all of which pass. 

I'm running Windows Insider: 20226.1000. Node.js: v14.12.0

For me, the version on npm produces the following error on first run.
```
C:\Users\Janice# serve
Serving static path: C:\Users\Janice
Generating certificates...
Certificates path: C:\Users\Janice\AppData\Roaming\https-localhost. Never modify nor share this files.
Downloading the mkcert executable...
http to https redirection active.
Running mkcert to generate certificates...
Certificates generated, installed and trusted. Ready to go!
Server running on port 443.
[Error: ENOENT: no such file or directory, open 'C:\Users\Janice\"C:\Users\Janice\AppData\Roaming\https-localhost\mkcert.log"'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Janice\\"C:\\Users\\Janice\\AppData\\Roaming\\https-localhost\\mkcert.log"'
}
[Error: ENOENT: no such file or directory, open 'C:\Users\Janice\"C:\Users\Janice\AppData\Roaming\https-localhost\mkcert.err"'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Janice\\"C:\\Users\\Janice\\AppData\\Roaming\\https-localhost\\mkcert.err"'
}
```
After installing the certificate in C:\Users\Janice\AppData\Roaming\https-localhost, running serve works perfectly.

**Comment by daquinoaldo** [comment]
Hi @NoelJacob,
thank you for the feedback.

The error at first run happens only with the public version, the latest release on npmjs.org, and not with the `fix-issue-28`, is that right?

If so, publishing the fix branch on npm should fix at least the missing file problem (i.e. the wrong path construction bug).

**Comment by daquinoaldo** [comment]
Hi @NoelJacob,
thank you for the feedback.

The error at first run happens only with the public version, the latest release on npmjs.org, and not with the `fix-issue-28`, is that right?

If so, publishing the fix branch on npm should fix at least the missing file problem (i.e. the wrong path construction bug).

**Comment by NoelJacob** [comment]
yes it should fix the problem

**Comment by yakunins** [comment]
Have same problem. So, I cloned `fix-issue-28`, run `npm install`, run `npm run test` and got exactly the same error:

```
Downloading the mkcert executable...
Running mkcert to generate certificates...
(node:15488) UnhandledPromiseRejectionWarning: Error: Command failed: ...
The process cannot access the file because it is being used by another process.
```

Windows 10, tested on both node v12 and node v14.

**Comment by daquinoaldo** [comment]
Hi @yakunins (and @Xeonzinc, @robokozo, @camous),

could you please try again on `fix-issue-38`?

1. Delete these two directories:
```
C:\Users\aldod\AppData\Roaming\https-localhost
C:\Users\aldod\AppData\Local\mkcert
```

2. Uninstall https-localhost and install the fix branch
```
# uninstall any version of https-localhost (if any)
npm i -g https-localhost

# install the fixed version directly from the GitHub branch
npm install -g git://github.com/daquinoaldo/https-localhost.git#fix-issue-28
```

I'm still not be able to reproduce the bug. I remove the log files. That should fix the `ENOENT`. Also, I added a 3 seconds sleep on Windows, even if it should be a sync call.
@yakunins tests should not be run in parallel and all async functions are awaited using the `done()` callback. Anyway, at runtime there is no parallelism at all.

Any further suggestion, feedback or other contribution is welcome.
Thank you for your cooperation.

**Comment by camous** [comment]
hey @daquinoaldo , sorry for not answering before :/

however, followed your instruction and it works for me. however is it exactly from an exact vanilla computer ? I will try on my other computer just after.
1. deleted 2 folders
2. uninstall
![image](https://user-images.githubusercontent.com/8566299/95631327-ceb69d80-0a83-11eb-91a3-4c880ceb6e9e.png)

3. install specific branch
![image](https://user-images.githubusercontent.com/8566299/95631378-e3933100-0a83-11eb-884d-b735db42968d.png)

4. serve
![image](https://user-images.githubusercontent.com/8566299/95631476-16d5c000-0a84-11eb-8e56-8b1f108ec53c.png)

5. success
![image](https://user-images.githubusercontent.com/8566299/95631548-366ce880-0a84-11eb-980f-409c8a49d96f.png)

**Comment by camous** [comment]
on a clean computer, running `serve` for the first time with **admistrator** permission with branch `git://github.com/daquinoaldo/https-localhost.git#fix-issue-28` it worked for me.

![image](https://user-images.githubusercontent.com/8566299/95632269-93b56980-0a85-11eb-956f-6861801c16f2.png)

![image](https://user-images.githubusercontent.com/8566299/95632354-c2334480-0a85-11eb-92ab-6e0046e07fdd.png)

**Comment by daquinoaldo** [comment]
Thank you, guys!
If someone still experiment this problem, feel free to comment this issue and we will discuss it again.

**Comment by yakunins** [comment]
@daquinoaldo Thank you, tests are passed.

![image](https://user-images.githubusercontent.com/2505676/95839999-1461b780-0d5d-11eb-8c10-6c09a1998747.png)

**Comment by daquinoaldo** [comment]
By the way, the fix has been released in v4.6.3.
